Link error fixed in Update README.md
tapexyz/tape pull request #1512
Opened 2024-11-09 10:45 UTC by mdqst

## Description

The link **Contributing Guidelines** has been corrected. The old one was giving a 404 error.
Right link is `https://github.com/tapexyz/tape/blob/0bc66629c6560ecf9cac4a8503be8619ff5eba27/.github/CONTRIBUTING.md`
Old link was `https://github.com/tapexyz/tape/blob/0bc66629c6560ecf9cac4a8503be8619ff5eba27/CONTRIBUTING.md`

- [x] I read the [contributing docs](CONTRIBUTING.md) (if this is your first contribution)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor changes in old functionality

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2024-11-09 16:57 UTC, sasicodes commented
we just need to link it to `.github/CONTRIBUTING.md`, instead of abs url

2024-11-09 16:59 UTC, sasicodes requested changes
https://github.com/tapexyz/tape/pull/1512#issuecomment-2466292931

2024-11-10 14:42 UTC, bigint commented on README.md
> +We love contributors! Feel free to contribute to this project but please read the [Contributing Guidelines](https://github.com/tapexyz/tape/blob/0bc66629c6560ecf9cac4a8503be8619ff5eba27/.github/CONTR
```suggestion
We love contributors! Feel free to contribute to this project but please read the [Contributing Guidelines](.github/CONTRIBUTING.md) before opening an issue or PR so you understand the branching strategy and local development environment.
```

2024-11-12 17:11 UTC, sasicodes approved these changes

2024-11-12 17:11 UTC, merged